
O = ../object

main: 	main.cpp $O/Event.o $O/Cours.o $O/Horaire.o $O/Professeur.o $O/Groupe.o $O/Local.o $O/Liste.o $O/Timing.o $O/Temps.o $O/Exception.o $O/TempsException.o $O/TimingException.o $O/planifiable.o $O/ListeTriee.o $O/Iterateur.o
		g++ -o main main.cpp $O/Event.o $O/Cours.o $O/Horaire.o $O/Professeur.o $O/Groupe.o $O/Local.o $O/Liste.o $O/Timing.o $O/Temps.o $O/Exception.o $O/TempsException.o $O/TimingException.o $O/planifiable.o $O/ListeTriee.o $O/Iterateur.o
